/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        panel: "var(--panel)",
        "panel-sunk": "var(--panel-sunk)",
        "panel-raised": "var(--panel-raised)",
        ink: "var(--ink)",
        "ink-soft": "var(--ink-soft)",
        rule: "var(--rule)",
        signal: "var(--signal)",
        "signal-tint": "var(--signal-tint)",
        telemetry: "var(--telemetry)",
        hardware: "var(--hardware)",
        // Theme mappings
        background: "var(--panel)",
        foreground: "var(--ink)",
        card: "var(--panel-raised)",
        "card-foreground": "var(--ink)",
        muted: "var(--panel-sunk)",
        "muted-foreground": "var(--ink-soft)",
        border: "var(--rule)",
        input: "var(--panel-sunk)",
        ring: "var(--signal)",
        primary: "var(--ink)",
        "primary-foreground": "var(--panel)",
        secondary: "var(--panel-sunk)",
        "secondary-foreground": "var(--ink)",
        accent: "var(--signal)",
        "accent-foreground": "var(--panel)",
      },
      fontFamily: {
        heading: ['"Saira Condensed"', 'sans-serif'],
        sans: ['"IBM Plex Sans"', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'monospace'],
      },
      borderRadius: {
        none: "0px",
        DEFAULT: "2px",
        sm: "2px",
        md: "2px",
        lg: "2px",
        xl: "2px",
        "2xl": "2px",
        "3xl": "2px",
        full: "2px",
      },
    },
  },
  plugins: [],
}
